# Generated by Django 2.2.2 on 2019-06-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qidaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qidaapp.University'),
        ),
        migrations.CreateModel(
            name='Degre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='degre name')),
                ('field', models.CharField(max_length=30, verbose_name='degre field')),
                ('participants', models.ManyToManyField(to='qidaapp.Student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qidaapp.University')),
            ],
        ),
    ]
